os: osx
osx_image: xcode11.2

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      name: "Build KhmerUnicode [Bundle]"
      script: make bundle
    - stage: build
      name: "Build KhmerUnicode [Installer]"
      cleanup: false
      install:
        - echo ">>> Prepare build environment"
        - sudo /usr/sbin/installer -pkg bin/Packages.pkg -target /
      script: make installer
    - stage: deploy
      deploy:
        provider: releases
        cleanup: false
        token: $GITHUB_OAUTH_TOKEN
        file: "build/KhmerUnicodeInstaller/Khmer Unicode Installer.pkg"
        on:
          tags: true
