os: osx

language: node_js
node_js:
  - "lts/*"

install:
  - echo ">>> Prepare build environment"
  - sudo /usr/sbin/installer -pkg bin/Packages.pkg -target /

script:
  - echo ">>> Building Khmer Unicode Installer"
  - ./build.sh

after_success:
  - echo ">>> Testing Khmer Unicode Installer"
  - sudo /usr/sbin/installer -pkg "build/Khmer Unicode Installer.pkg" -target /

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "build/Khmer Unicode Installer.pkg"
  skip_cleanup: true
  on:
    tags: true
