os: osx

language: node_js
node_js:
  - "lts/*"

env:
  - CONFIGURATION_BUILD_DIR="${TRAVIS_BUILD_DIR}/build"

install:
  - echo ">>> Prepare build environment"
  - sudo /usr/sbin/installer -pkg bin/Packages.pkg -target /

before_script:
  - echo "TRAVIS_BUILD_DIR= $TRAVIS_BUILD_DIR"
  - echo "CONFIGURATION_BUILD_DIR= $CONFIGURATION_BUILD_DIR"

script:
  - echo ">>> Building Khmer Unicode Installer"
  - make

after_success:
  - echo ">>> Testing Khmer Unicode Installer"
  - sudo /usr/sbin/installer \
    -pkg "build/KhmerUnicodeInstaller/Khmer Unicode Installer.pkg" \
    -target /

deploy:
  provider: releases
  cleanup: false
  token: $GITHUB_OAUTH_TOKEN
  file: "build/KhmerUnicodeInstaller/Khmer Unicode Installer.pkg"
  on:
    tags: true
