os: osx

language: node_js
node_js:
  - "lts/*"

install:
  - echo ">>> Prepare build environment"
  - sudo /usr/sbin/installer -pkg bin/Packages.pkg -target /

script:
  - echo ">>> Building Khmer Unicode Installer"
  - make

after_success:
  - echo ">>> Testing Khmer Unicode Installer"
  - sudo /usr/sbin/installer \
    -pkg "build/KhmerUnicodeInstaller/Khmer Unicode Installer.pkg" \
    -target /

deploy:
  provider: releases
  cleanup: false
  token: $GITHUB_OAUTH_TOKEN
  file: "build/KhmerUnicodeInstaller/Khmer Unicode Installer.pkg"
  on:
    tags: true
