os: osx

language: node_js
node_js:
  - "lts/*"

install:
  - sudo /usr/sbin/installer -pkg bin/Packages.pkg -target /

script:
  - ./build.sh

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "build/Khmer Unicode Installer.pkg"
  skip_cleanup: true
  on:
    tags: true
