name: Build Xcode Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Integrated packaging environment (packages)
        run: brew install packages

      - name: Build KhmerUnicode.bundle
        run: make build

      - name: Build KhmerUnicode installer
        run: make installer
